# Generated by Django 2.2.2 on 2019-06-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TUDO',
        ),
    ]
